name: election_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  shared_preferences: ^2.0.8
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  equatable: ^2.0.3
  dartz: ^0.10.1
  flutter_vector_icons: ^1.0.0
  logger: ^1.1.0
  rxdart: ^0.27.2
  window_manager: ^0.2.5

  size_config:
    git:
      url: https://github.com/MohamedNajib/size_config.git
      ref: v1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200